apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-app
  name: inventory-app-service
  namespace: inventory-prod
spec:
  clusterIP: 10.107.138.48
  clusterIPs:
    - 10.107.138.48
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: inventory-app
  sessionAffinity: None
  type: ClusterIP
