apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: inventory-prod
type: Opaque
data:
  POSTGRES_USER: YWRtaW4= # base64 encoded value
  POSTGRES_PASSWORD: YWRtaW4= # base64 encoded value
  POSTGRES_DB: aW52ZW50b3J5X2FwcA== # base64 encoded value  
  DB_USER: YWRtaW4=          # same value, app reads this key
  DB_PASSWORD: YWRtaW4=      # same value, app reads this key

