apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: inventory-prod
type: Opaque
data:
  # REDIS_PASSWORD: YWRtaW4= # base64 encoded value
  # REDIS_USERNAME: YWRtaW4= # base64 encoded value 
  REDIS_HOST: cmVkaXM= # base64 encoded value 
  REDIS_PORT: NjM3OQ== # base64 encoded value

stringData:
  REDIS_PASSWORD: ""
  REDIS_USERNAME: ""


      